# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.adapt_theta_adapt_tau <- function(Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, nu_tau, lambda_tau, nu_sigma, lambda_sigma, a, b, N_u, rho_eta, M, nd, burn, verbose, print_every, debug = FALSE) {
    .Call('_splineBART_adapt_theta_adapt_tau', PACKAGE = 'splineBART', Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, nu_tau, lambda_tau, nu_sigma, lambda_sigma, a, b, N_u, rho_eta, M, nd, burn, verbose, print_every, debug)
}

.adapt_theta_fixed_tau <- function(Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, tau, nu_sigma, lambda_sigma, a, b, N_u, rho_eta, M, nd, burn, verbose, print_every, debug = FALSE) {
    .Call('_splineBART_adapt_theta_fixed_tau', PACKAGE = 'splineBART', Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, tau, nu_sigma, lambda_sigma, a, b, N_u, rho_eta, M, nd, burn, verbose, print_every, debug)
}

.fixed_theta_adapt_tau <- function(Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, nu_tau, lambda_tau, nu_sigma, lambda_sigma, M, nd, burn, verbose, print_every, debug = FALSE) {
    .Call('_splineBART_fixed_theta_adapt_tau', PACKAGE = 'splineBART', Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, nu_tau, lambda_tau, nu_sigma, lambda_sigma, M, nd, burn, verbose, print_every, debug)
}

.fixed_theta_fixed_tau <- function(Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, tau, nu_sigma, lambda_sigma, M, nd, burn, verbose, print_every, debug = FALSE) {
    .Call('_splineBART_fixed_theta_fixed_tau', PACKAGE = 'splineBART', Y_train, Phi_train, Z_train, Z_test, cutpoints, alpha, beta, K, log_det_K, rank_K, tau, nu_sigma, lambda_sigma, M, nd, burn, verbose, print_every, debug)
}

.summarize_fit <- function(beta_list, Phi_list, probs, n_samples, y_mean, y_sd) {
    .Call('_splineBART_summarize_fit', PACKAGE = 'splineBART', beta_list, Phi_list, probs, n_samples, y_mean, y_sd)
}

.summarize_fit_ystar <- function(beta_list, Phi_list, sigma_list, probs, n_samples, y_mean, y_sd) {
    .Call('_splineBART_summarize_fit_ystar', PACKAGE = 'splineBART', beta_list, Phi_list, sigma_list, probs, n_samples, y_mean, y_sd)
}

